services:
  npm:
    build: ./docker/npm
    environment:
      TZ: Asia/Tokyo
    ports:
      - 5173:5173
    volumes:
      - .:/app
    working_dir: /app
    init: true
    stop_signal: SIGHUP
    entrypoint: ["npm"]
    command: ["run","dev"]
